"""Guide text used by the Nano Logic TUI."""
from __future__ import annotations


def render_guide() -> str:
    """Return a short in-app guide for available DSL commands."""
    lines = [
        "Guide for NanoLogic",
        "",
        "CPU Commands",
        "- cpu.util: CPU usage %",
        "- cpu.load: 1/5/15m load avg",
        "- cpu.cores: CPU cores info",
        "- cpu.top: Top 5 CPU processes",
        "- cpu.avg: Normalised load %",
        "",
        "Memory Commands",
        "- mem.util: Memory usage %",
        "- mem.stats: Memory details",
        "- mem.swap: Swap memory info",
        "- mem.top: Top 5 memory procs",
        "- mem.cached: Cached/buffers",
        "",
        "Disk Commands",
        "- disk.free: Root FS free space",
        "- disk.usage: All partitions %",
        "- disk.io: I/O stats",
        "- disk.top: Dir storage usage",
        "- disk.inode: Inode usage %",
        "",
        "GPU Commands",
        "- gpu.util: GPU util & mem",
        "",
        "Process Commands",
        "- proc.list: List processes",
        "- proc.kill <pid>: Kill process",
        "- proc.search <name>: Find proc",
        "- proc.tree: Process tree view",
        "- proc.info <pid>: Proc details",
        "",
        "Network Commands",
        "- net.interfaces: Net ifaces",
        "- net.bandwidth: Net stats",
        "- net.connections: Active conns",
        "- net.ports: Listening ports",
        "- net.dns <host>: DNS lookup",
        "",
        "System Commands",
        "- system.uptime: System uptime",
        "- system.info: OS/hostname info",
        "- system.processes: Proc/thread cnt",
        "- system.users: Logged-in users",
        "- system.load: Load overview",
        "",
        "Sensor Commands",
        "- sensor.temp: CPU/device temps",
        "- sensor.fans: Fan speeds (RPM)",
        "- sensor.battery: Battery %",
        "",
        "Docker Commands",
        "- docker.ps: Running containers",
        "- docker.stats: Container stats",
        "- docker.info: Daemon/system info",
        "- docker.images: Stored images",
        "- docker.containers: All containers",
        "- docker.logs <name>: Container logs",
        "- docker.networks: Docker networks",
        "- docker.volumes: Docker volumes",
        "",
        "Service Commands",
        "- service.list: Running services",
        "- service.status <name>: Svc status",
        "",
        "Utility Commands",
        "- clear: Clear console",
        "- help: Show all commands",
        "- rules: List active rules",
        "- status: System overview",
        "- history: Command history",
        "- guide: Show this guide",
        "",
        "Alert Syntax",
        "- <name>: alert <metric> <op> <val> -> <action>",
        "- stop [rule] <id|name>",
        "- Operators: > < == >= <=",
        "- Actions: log (more coming)",
        "",
        "Tips",
        "- Press q to quit",
        "- Up/down arrows for history",
    ]
    return "\n".join(lines)
